### ISSUE TITLE
Call failure on startup breaks complete UI

### ISSUE THREAD

**Issue by JamieSterling** [klattimer/SystemDashboard#20]
Seems to be when a call fails the JS won't continue and just errors out, causing the UI to not load completely.

Looking into adding better error handling.

**Comment by JamieSterling** [comment]
For reference.

First call error:
![Screenshot 2019-04-16 at 12 30 17](https://user-images.githubusercontent.com/5941225/56206109-7d228380-6043-11e9-9034-8299586e39a8.png)

Some hookery shows some components working:
![Screenshot 2019-04-16 at 12 30 24](https://user-images.githubusercontent.com/5941225/56206147-95929e00-6043-11e9-8a2e-b311fc15eef5.png)

**Comment by klattimer** [comment]
I think you fixed this, closing.
